### ISSUE TITLE
Remove the "rejected" status from the ProposalStatus enum

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-parachain#19]
### Context

Following from discussion #16 , it is no longer needed to have this property. It should be removed to make the Project struct simple.

**Comment by Immanuel-john** [comment]
I have started contributing to this, hope the code which i need to work is Main branch?

**Comment by islami00** [comment]
Yes, you can work off of the main branch :+1:

**Comment by Immanuel-john** [comment]
Hi. I have created a Pull Request for the same [here](https://github.com/chocolatenetwork/chocolate-parachain/pull/27) 
Kindly do a review and expecting feedbacks if any. thank you

**Comment by islami00** [comment]
I've reviewed the Pr and merged

I will now be closing the issue, Thank you for contributing!
