### ISSUE TITLE
Simplify chocolate pallet

### ISSUE THREAD

**Issue by islami00** [chocolatenetwork/chocolate-parachain#6]
### Scope

Probably milestone 2, after migrations

### Aim

The goal of this issue is to make the chocolate pallet better capture the MVP [here](https://github.com/chocolatenetwork/chocolate-parachain/discussions/16#discussioncomment-3388802)

1. Refactor `review` methods out  to users pallet and rename the pallet to project pallet. 
2. Improve the coherence of the chocolate pallet e.g `ProjectIO` and `UserIO` traits, by grouping and refactoring methods to capture the core process involved in it.
3. Include test cases for the Project creation  process

Further Ideas around improving this pallet to make it easier to perform its core actions in code are welcome.

**Comment by johnagentify** [comment]
Hi @islami00 . I would like to contribute to this issue. could you please help me to understand the first 2 points in more detail?

**Comment by islami00** [comment]
Hi @Immanuel-john , 

1. For the first point, the chocolate pallet has some logic for projects (via [extrinsics](https://github.com/Immanuel-john/chocolate-parachain/blob/320abbc21eaa0a0da0868812bfbfea7b617cba5e/pallets/chocolate/src/lib.rs#L153-L181) and the [ProjectIO](https://github.com/Immanuel-john/chocolate-parachain/blob/320abbc21eaa0a0da0868812bfbfea7b617cba5e/pallets/chocolate/src/lib.rs#L295) trait) and reviews ([extrinsics](https://github.com/Immanuel-john/chocolate-parachain/blob/320abbc21eaa0a0da0868812bfbfea7b617cba5e/pallets/chocolate/src/lib.rs#L181-L268) and in [this impl block](https://github.com/Immanuel-john/chocolate-parachain/blob/320abbc21eaa0a0da0868812bfbfea7b617cba5e/pallets/chocolate/src/lib.rs#L425-L460)), the goal is to move the methods related to reviews out to the users pallet as it'll only be used by users , and then rename the chocolate pallet to the project pallet as it'll only have methods related to projects.

2. For the second point, there are some stray functions in the [impl for the Pallet](https://github.com/Immanuel-john/chocolate-parachain/blob/320abbc21eaa0a0da0868812bfbfea7b617cba5e/pallets/chocolate/src/lib.rs#L366-L460) that are somewhat duplicates of the methods in [ProjectIO](https://github.com/Immanuel-john/chocolate-parachain/blob/320abbc21eaa0a0da0868812bfbfea7b617cba5e/primitives/src/projects.rs#L170) trait but more specific to Users and reviews. The aim is to explicitly group those methods.

You could think of the second point as grouping the stray impl block for Pallet<T> into its own trait (Probably named `ReviewIO`), and the first point as finally moving anything review related to the users' pallet.

Let me know if you have any further doubts

**Comment by johnagentify** [comment]
@islami00 ,

Thanks for the clarification. Why not have the reviews and projects related extrinsics and methods in same pallet but with different traits implementation. Consider for an example if we have a DEX pallet and we won't separate deposit in one pallet and withdraw in another pallet, right? since the functionality is binded to DEX we will have a common pallet with respective traits maybe. So I assume projects and reviews are coupled to each other right? why not have them in same pallet in one common name and differentiate traits respectively. this is entirely my opinion and I may be wrong. What do you think?

**Comment by islami00** [comment]
@Immanuel-john ,

Yes, I agree with this, both are coupled and should remain in the same pallet under different traits.

Thanks for the dex example as well, it captures this case really well, I have no objections.

**Comment by johnagentify** [comment]
Great. Ok then let me try to refactor the same in a single pallet.

**Comment by johnagentify** [comment]
Hey @islami00 I was very well occupied for few months. Is this issue still valid?

**Comment by islami00** [comment]
Hello @Immanuel-john , thank you for following up, 
This issue is no longer valid, the majority of development effort is now on the design and implementation of [Chocolate Contract](https://github.com/chocolatenetwork/chocolate-contract)  (Still in the design/setup phase)

**Comment by johnagentify** [comment]
@islami00 is there any documentation for understanding the project so that I can contribute?

**Comment by islami00** [comment]
We’re changing the direction of the project so there's not a lot of documentation available right now, 
However, we'll keep you posted when more context is available. Thanks!
